### ISSUE TITLE
ammonite style import $file, import $exec, import $ivy

### ISSUE THREAD

**Issue by bulent2k2** [litan/kojo#22]
Would it make sense to enhance Kojo to support modular scripting features in ammonite like import $file, $exec and $ivy?

Is there an alternative available to use now for modular development of bigger scripts in Kojo?

**Comment by litan** [comment]
The enhancement might be difficult because of the need to support both compilation and interpretation.

For importing, Kojo has:
// #include file.kojo

For using external libs, Kojo has the libk mechanism. Anything under ~/.kojo/lite/libk is on the classpath.
