### ISSUE TITLE
Windows 10 Install4J (64-bit)

### ISSUE THREAD

**Issue by ddugovic** [litan/kojo#49]
Please advise what I can try to avoid this installation error (maybe I need to contact Install4J developers?):
![image](https://user-images.githubusercontent.com/1834123/137269328-c65b76be-ed8b-4695-ad21-783bb68afb6e.png)

**Comment by litan** [comment]
Hmm. Never seen this before. Please share the log file mentioned in the error message.

**Comment by litan** [comment]
A couple of things to try:
* https://www.papercut.com/kb/Main/AssistiveTechnologynotfound#the-cause
* https://stackoverflow.com/questions/15260989/exception-in-thread-main-java-awt-awterror-assistive-technology-not-found

**Comment by litan** [comment]
> Thanks, that resolved my issue!
Good to know...
