### ISSUE TITLE
Latest release hangs on macOS at the splash screen

### ISSUE THREAD

**Issue by bulent2k2** [litan/kojo#73]
It gets stuck at the splash screen (displaying the circle of colorful squares and the text: Loading...) and Kojo never starts up.

Version: 2.9.22

Tried on two machines:
1) MacBook Pro laptop running macOS Monterey Version 12.5 and 
2) MacBook Air running macOS Catalina Version 10.15.7

My own build from the latest comes up fine on machine (1).

**Comment by bulent2k2** [comment]
I also tried a couple of Windows machines and they work fine.

**Comment by bulent2k2** [comment]
Could it be due to the commit on Jun 26th: [Bump up JRE to 11.0.15](https://github.com/litan/kojo/commit/9bc1499d20d8ee2a0e8929941d0d85eb92613294)

**Comment by litan** [comment]
Please attach the Kojo log file (~/.kojo/lite/log/kojo0.log) after a hang.

**Comment by bulent2k2** [comment]
I confirmed that 2.9.21 works fine.
Here is the log file:
[kojo0.log](https://github.com/litan/kojo/files/9227168/kojo0.log)

Here is the error at the end:

```
[Sat Jul 30 15:29:43 EDT 2022, CodeExecutionSupport] SEVERE: stderr> java.lang.Error: no ComponentUI class for: javax.swing.JTextPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,kit=,typeHandlers=]
[Sat Jul 30 15:29:43 EDT 2022, CodeExecutionSupport] SEVERE: stderr> Exception in thread "AWT-EventQueue-0" 
[Sat Jul 30 15:29:43 EDT 2022, CodeExecutionSupport] SEVERE: stderr> Exception in thread "AWT-EventQueue-0" 

```

**Comment by litan** [comment]
Must be the JRE. Will get to this tomorrow and do a new release.
Thanks for reporting.

**Comment by litan** [comment]
Hi Bulent, please try the new release from here:
https://github.com/litan/kojo/releases/tag/2.9.23_release

Let me know if this works fine on your Macs.

**Comment by bulent2k2** [comment]
It works fine, Lalit. Thank you!
