### ISSUE TITLE
Exception when using a touch screen laptop

### ISSUE THREAD

**Issue by bulent2k2** [litan/kojo#82]
The exception happens when we touch the canvas during Showcase/Tic Tac Toe (or Othello) instead of using the left mouse button to click. The good news is that it doesn't break the game. However, each touch event results in an exception and a long stack trace. 

Note that touching the Run button on the script editor works OK. 

Here is the log file:

[error-at-first-touch-tic-tac-toe.log](https://github.com/litan/kojo/files/9551441/error-at-first-touch-tic-tac-toe.log)

**Comment by litan** [comment]
This looks to be triggered by an event that Piccolo2D (the scene graph lib under the drawing canvas) does not recognize. 
Will investigate...

**Comment by litan** [comment]
I have an initial fix for this. Please try it out @bulent2k2.

**Comment by bulent2k2** [comment]
I just verified that the fix works on my ChromeOS tablet. Thanks so much Lalit.

**Comment by bulent2k2** [comment]
On the otherhand, it looks like this fix disables the roll wheel (or two finger swipe on the touch pad) to Zoom :-(

I checked it on MacOS, and it has the same issue.

**Comment by litan** [comment]
Ah, we can't have that!
I'll get access to a touch device running Kojo in a day or two. Will explore further then...

**Comment by litan** [comment]
Had a thought, checked in a (theoretical) refinement to the earlier fix.
Please give this one a try, @bulent2k2.

**Comment by bulent2k2** [comment]
This one works, Lalit! Verified that the roll wheel (or two finger swipe) works for zooming in and out. And, there is no stack dump due to exceptions.

Thank you very much!

**Comment by litan** [comment]
Sounds good!
